export const FETCH_MESSAGES_REQUEST="FETCH_MESSAGES_REQUEST";
export const FETCH_MESSAGES_SUCCESS="FETCH_MESSAGES_SUCCESS";
export const FETCH_MESSAGES_FAILURE="FETCH_MESSAGES_FAILURE";


export const SEND_MESSAGES_REQUEST="SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS="SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_FAILURE="SEND_MESSAGES_FAILURE";


export const FETCH_CHAT_BY_PROEJECT_REQUEST="FETCH_CHAT_BY_PROEJECT_REQUEST";
export const FETCH_CHAT_BY_PROEJECT_SUCCESS="FETCH_CHAT_BY_PROEJECT_SUCCESS";
export const FETCH_CHAT_BY_PROEJECT_FAILURE="FETCH_CHAT_BY_PROEJECT_FAILURE";

export const FETCH_CHAT_MESSAGES_REQUEST="FETCH_CHAT_MESSAGES_REQUEST";
export const FETCH_CHAT_MESSAGES_SUCCESS="FETCH_CHAT_MESSAGES_SUCCESS";
export const FETCH_CHAT_MESSAGES_FAILURE="FETCH_CHAT_MESSAGES_FAILURE";
